

-- CREATE TABLES

CREATE TABLE "User" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" VARCHAR,
  "last_name" VARCHAR,
  "username" varchar UNIQUE,
  "email" varchar,
  "password_hash" varchar,
  "device_token" varchar,
  "auth_provider" varchar DEFAULT 'local',
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "feature_flags" text[] NOT NULL DEFAULT ARRAY[]::text[]
); 

CREATE TABLE "Admin" (
  "admin_id" int PRIMARY KEY,
  "role" VARCHAR(255)
);

CREATE TABLE "Mantra" (
  "mantra_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "key_takeaway" text,
  "background_author" varchar,
  "background_description" text,
  "jamie_take" text,
  "when_where" text,
  "negative_thoughts" text,
  "cbt_principles" text,
  "references" text,
  "created_by" int,
  "is_active" boolean,
  "created_at" timestamp
);

CREATE TABLE "Category" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" TEXT,
  "category_type" VARCHAR(50), -- 'essential', 'goal', 'mood', 'scenario', 'time', 'theme'
  "parent_id" INT REFERENCES "Category"("category_id") ON DELETE SET NULL,
  "image_url" VARCHAR, -- optional thumbnail for UI
  "is_active" BOOLEAN DEFAULT TRUE
);

CREATE TABLE "MantraCategory" (
  "mantra_id" int,
  "category_id" int,
  PRIMARY KEY(mantra_id,category_id)
);

CREATE TABLE "Like" (
  "like_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "mantra_id" int,
  "created_at" timestamp
);

CREATE TABLE "Collection" (
  "collection_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar,
  "description" text,
  "created_at" timestamp
);

CREATE TABLE "CollectionMantra" (
  "collection_id" int,
  "mantra_id" int,
  "added_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "added_by" INT,
  PRIMARY KEY(collection_id,mantra_id)
);

CREATE TABLE "Reminder" (
  "reminder_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "mantra_id" int,
  "collection_id" int,
  "time" timestamp,
  "frequency" varchar,
  "status" varchar,
  "last_sent_at" timestamp
);

CREATE TABLE "RecommendationLog" (
  "rec_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "mantra_id" int,
  "timestamp" timestamp,
  "reason" text
);

CREATE TABLE "PasswordResetToken" (
  "token_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "code" VARCHAR(72) NOT NULL,
  "expires_at" TIMESTAMP NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Rating" (
  "rating_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "mantra_id" int NOT NULL,
  "rating" int NOT NULL CHECK (rating >= 1 AND rating <= 5),
  "review_text" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_user_mantra_rating UNIQUE(user_id, mantra_id)
);

CREATE TABLE "PerformanceEvent" (
  "event_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kind" VARCHAR(50) NOT NULL,
  "name" VARCHAR(120) NOT NULL,
  "duration_ms" DOUBLE PRECISION NOT NULL,
  "status" VARCHAR(16) NOT NULL,
  "source" VARCHAR(16) NOT NULL,
  "route" VARCHAR(200),
  "method" VARCHAR(12),
  "screen" VARCHAR(80),
  "request_id" VARCHAR(80),
  "platform" VARCHAR(50),
  "app_version" VARCHAR(50),
  "metadata" JSONB,
  "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_performance_event_occurred_at
  ON "PerformanceEvent" ("occurred_at" DESC);

CREATE INDEX idx_performance_event_kind
  ON "PerformanceEvent" ("kind");

CREATE INDEX idx_performance_event_source
  ON "PerformanceEvent" ("source");

ALTER TABLE "Admin" ADD FOREIGN KEY ("admin_id") REFERENCES "User" ("user_id");

ALTER TABLE "Mantra" ADD FOREIGN KEY ("created_by") REFERENCES "Admin" ("admin_id");

ALTER TABLE "MantraCategory" ADD FOREIGN KEY ("mantra_id") REFERENCES "Mantra" ("mantra_id");

ALTER TABLE "MantraCategory" ADD FOREIGN KEY ("category_id") REFERENCES "Category" ("category_id");

ALTER TABLE "Like" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Like" ADD FOREIGN KEY ("mantra_id") REFERENCES "Mantra" ("mantra_id");

ALTER TABLE "Collection" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "CollectionMantra" ADD FOREIGN KEY ("collection_id") REFERENCES "Collection" ("collection_id");

ALTER TABLE "CollectionMantra" ADD FOREIGN KEY ("mantra_id") REFERENCES "Mantra" ("mantra_id");

ALTER TABLE "CollectionMantra" ADD FOREIGN KEY ("added_by") REFERENCES "User" ("user_id");

ALTER TABLE "Reminder" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Reminder" ADD FOREIGN KEY ("mantra_id") REFERENCES "Mantra" ("mantra_id");

ALTER TABLE "Reminder" ADD FOREIGN KEY ("collection_id") REFERENCES "Collection" ("collection_id");

ALTER TABLE "RecommendationLog" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "RecommendationLog" ADD FOREIGN KEY ("mantra_id") REFERENCES "Mantra" ("mantra_id");

ALTER TABLE "PasswordResetToken" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id") ON DELETE CASCADE;
ALTER TABLE "Rating" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Rating" ADD FOREIGN KEY ("mantra_id") REFERENCES "Mantra" ("mantra_id");
