-- Journal Entry Migration

CREATE TABLE "JournalEntry" (
  "journal_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "mantra_id" INT,
  "title" VARCHAR(255),
  "content" TEXT NOT NULL,
  "mood" VARCHAR(50),
  "tags" TEXT[],
  "is_private" BOOLEAN DEFAULT TRUE,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- foreign keys to associate to mantras and users
ALTER TABLE "JournalEntry" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id") ON DELETE CASCADE;
ALTER TABLE "JournalEntry" ADD FOREIGN KEY ("mantra_id") REFERENCES "Mantra" ("mantra_id") ON DELETE SET NULL;

-- indexing for faster query
CREATE INDEX idx_journal_user_id ON "JournalEntry" ("user_id");
CREATE INDEX idx_journal_mantra_id ON "JournalEntry" ("mantra_id");
CREATE INDEX idx_journal_created_at ON "JournalEntry" ("created_at" DESC);

COMMENT ON TABLE "JournalEntry" IS 'Stores user journal entries associated with mantras for reflection and personal growth tracking';
