FROM node:22

#install pnpm globally
RUN npm i -g pnpm@9.12.0

#Setting app directory
WORKDIR /app

#copy package.json and package-lock.json
COPY package*.json ./

#install dependencies
RUN pnpm install

COPY . .

#setting port environment variable
ENV PORT=9000

#exposing port for env var
EXPOSE 9000

#Run CMD
CMD ["pnpm", "start"]

