import React, { useState } from 'react';
import { View, ScrollView, TouchableOpacity } from 'react-native';
import { useTheme } from '../context/ThemeContext';
import AppText from '../components/UI/textWrapper';
import { storage } from '../utils/storage';

export default function TermsOfUseScreen({ navigation }: any) {
  const { colors } = useTheme();
  const [agreed, setAgreed] = useState(false);

  const handleAccept = async () => {
    await storage.setTermsAccepted();
    navigation.reset({
      index: 0,
      routes: [{ name: 'MainApp' }],
    });
  };

  return (
    <View style={{ flex: 1, backgroundColor: colors.primary }}>
      <View style={{ paddingTop: 60, paddingHorizontal: 20, paddingBottom: 12 }}>
        <AppText
          style={{ color: colors.white, fontSize: 24, fontWeight: 'bold', textAlign: 'center' }}
        >
          Terms of Use
        </AppText>
      </View>

      <ScrollView
        style={{ flex: 1, marginHorizontal: 16 }}
        contentContainerStyle={{
          backgroundColor: colors.white,
          borderRadius: 12,
          padding: 20,
          marginBottom: 16,
        }}
        showsVerticalScrollIndicator
      >
        <AppText style={{ fontSize: 15, color: '#333', lineHeight: 22, marginBottom: 14 }}>
          By using MeMantra, you agree to the following Terms of Use. If you do not agree, please do
          not use the App.
        </AppText>

        <AppText
          style={{
            fontSize: 17,
            fontWeight: '600',
            color: colors.primary,
            marginBottom: 8,
            marginTop: 8,
          }}
        >
          1. User-Generated Content
        </AppText>
        <AppText style={{ fontSize: 15, color: '#333', lineHeight: 22, marginBottom: 14 }}>
          MeMantra includes an AI-powered chat assistant. AI responses are generated by OpenAI and
          are not professional medical, psychological, or legal advice. You are solely responsible
          for the content you submit. All content is processed through OpenAI's content filtering
          systems.
        </AppText>

        <AppText
          style={{
            fontSize: 17,
            fontWeight: '600',
            color: colors.primary,
            marginBottom: 8,
            marginTop: 8,
          }}
        >
          2. Zero-Tolerance Content Policy
        </AppText>
        <AppText style={{ fontSize: 15, color: '#333', lineHeight: 22, marginBottom: 14 }}>
          MeMantra enforces a zero-tolerance policy for objectionable content. You may not harass,
          bully, or threaten other users; post sexually explicit, violent, or hateful content;
          promote self-harm or illegal activities; or impersonate others. Violations will result in
          account termination.
        </AppText>

        <AppText
          style={{
            fontSize: 17,
            fontWeight: '600',
            color: colors.primary,
            marginBottom: 8,
            marginTop: 8,
          }}
        >
          3. Reporting & Blocking
        </AppText>
        <AppText style={{ fontSize: 15, color: '#333', lineHeight: 22, marginBottom: 14 }}>
          If you encounter objectionable content, you can report any message by long-pressing it and
          selecting "Report". You can also delete any conversation at any time. All reports are
          reviewed within 24 hours.
        </AppText>

        <AppText
          style={{
            fontSize: 17,
            fontWeight: '600',
            color: colors.primary,
            marginBottom: 8,
            marginTop: 8,
          }}
        >
          4. Account Termination
        </AppText>
        <AppText style={{ fontSize: 15, color: '#333', lineHeight: 22, marginBottom: 14 }}>
          We reserve the right to suspend or permanently terminate any account that violates these
          Terms, with or without prior notice.
        </AppText>

        <AppText
          style={{
            fontSize: 17,
            fontWeight: '600',
            color: colors.primary,
            marginBottom: 8,
            marginTop: 8,
          }}
        >
          5. Disclaimer
        </AppText>
        <AppText style={{ fontSize: 15, color: '#333', lineHeight: 22, marginBottom: 14 }}>
          MeMantra is provided "as is" without warranties of any kind. The AI chat feature is not a
          substitute for professional advice.
        </AppText>

        <AppText style={{ fontSize: 13, color: '#888', marginTop: 10 }}>
          Full terms available at memantra.onrender.com/terms-of-use
        </AppText>
      </ScrollView>

      <View style={{ paddingHorizontal: 20, paddingBottom: 40 }}>
        <TouchableOpacity
          onPress={() => setAgreed(!agreed)}
          style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 16 }}
          activeOpacity={0.7}
        >
          <View
            style={{
              width: 24,
              height: 24,
              borderRadius: 6,
              borderWidth: 2,
              borderColor: colors.white,
              backgroundColor: agreed ? colors.secondary : 'transparent',
              alignItems: 'center',
              justifyContent: 'center',
              marginRight: 10,
            }}
          >
            {agreed && (
              <AppText style={{ color: colors.white, fontSize: 14, fontWeight: 'bold' }}>✓</AppText>
            )}
          </View>
          <AppText style={{ color: colors.white, fontSize: 15, flex: 1 }}>
            I have read and agree to the Terms of Use
          </AppText>
        </TouchableOpacity>

        <TouchableOpacity
          onPress={handleAccept}
          disabled={!agreed}
          style={{
            backgroundColor: agreed ? colors.secondary : `${colors.secondary}50`,
            borderRadius: 30,
            padding: 14,
            alignItems: 'center',
          }}
        >
          <AppText style={{ color: '#fff', fontSize: 18, fontWeight: '600' }}>Continue</AppText>
        </TouchableOpacity>
      </View>
    </View>
  );
}
